import { test, expect } from '@playwright/test';
test('cloud menu is available at project and folder level without launching on account discovery', async ({ page }) => {
 const posts: unknown[] = [];
 await page.addInitScript(() => { localStorage.setItem('orb.apiUrl', location.origin); localStorage.setItem('orb.jwt','test'); });
 await page.route('**/api/**', async route => {
  const request = route.request(), url = new URL(request.url()), path = url.pathname;
  if (request.method() === 'POST' && path === '/api/control/missions') posts.push(request.postDataJSON());
  if (path === '/api/control/stream') return route.fulfill({contentType:'text/event-stream',body:''});
  let json: unknown = {};
  if (path === '/api/projects') json = {projects:[{slug:'demo',title:'Demo'}]};
  else if (path === '/api/cloud/accounts') json = [{id:'grok',provider:'grok_bot',label:'Grok Bot',available:false,experimental:true,reason:'Protocol compatibility not validated',capabilities:{}}];
  else if (path === '/api/control/missions' || path === '/api/control/queue' || path === '/api/backends') json = [];
  else if (path.endsWith('/files')) json = {entries: url.searchParams.get('path') ? [] : [{name:'notes',kind:'dir'}]};
  else if (path.endsWith('/crons')) json = {jobs:[]};
  else if (path.includes('/controller')) json = {job:null,runs:[]};
  else if (path === '/api/providers/backend-models') json = {backends:{}};
  return route.fulfill({json});
 });
 await page.goto('/');
 await page.getByRole('button',{name:'Project actions for Demo'}).click();
 await page.getByRole('menuitem',{name:'Cloud agent',exact:true}).click();
 const dialog = page.locator('main').getByRole('region',{name:'Cloud agent'});
 await expect(page.getByRole('dialog')).toHaveCount(0);
 await expect(page.getByRole('button',{name:'Cloud agent',exact:true})).toHaveClass(/active/);
 await expect(dialog).toBeVisible();
 await expect(page.locator('main .composer')).toHaveCount(1);
 await expect(page.getByPlaceholder('Describe a task, / for commands, @ for context')).toHaveCount(0);
 await dialog.getByLabel('Service').click();
 await dialog.getByRole('menuitemradio',{name:'Grok Bot'}).click();
 await expect(dialog.getByLabel('Experimental connector')).toBeVisible();
 await expect(dialog.getByText('Protocol compatibility not validated')).toBeVisible();
 await expect(dialog.getByRole('button',{name:'Create cloud agent'})).toBeDisabled();
 await page.getByRole('button',{name:/New Agent/}).click();
 await expect(dialog).toHaveCount(0);
 // Expand via the visible project tree row when it is initially collapsed.
 const folder = page.getByRole('button',{name:'Folder actions for notes'});
 if (!(await folder.isVisible())) await page.getByRole('button',{name:'Demo',exact:true}).click();
 await folder.click();
 await page.getByRole('menuitem',{name:'Cloud agent',exact:true}).click();
 await expect(dialog.getByText('/ notes',{exact:true})).toBeVisible();
 await dialog.getByLabel('Service').click();
 await dialog.getByRole('menuitemradio',{name:'Grok Bot'}).click();
 await expect(dialog.getByText('Protocol compatibility not validated')).toBeVisible();
 await page.reload();
 await expect(page.getByRole('region',{name:'Cloud agent'})).toBeVisible();
 await expect(page.getByRole('dialog')).toHaveCount(0);
 expect(posts).toEqual([]);
 await dialog.getByLabel('Service').click();
 await dialog.getByRole('menuitemradio',{name:'Grok Bot'}).click();
 await page.screenshot({path:'screenshots/cloud-agent-page.png',fullPage:true});
});

test('reopening Orb retains the provider identity, result and follow-up target', async ({page}) => {
 const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
 const mission={id,title:'Cloud proof',backend:'cloud_cursor',project:'demo',status:'awaiting_user',history:[],created_at:'',updated_at:''};
 const followups: any[]=[];
 let observations=0;
 await page.addInitScript(() => {localStorage.setItem('orb.apiUrl',location.origin);localStorage.setItem('orb.jwt','test');});
 await page.route('**/api/**',async route => {
  const request=route.request(),path=new URL(request.url()).pathname;
  if(path==='/api/control/stream')return route.fulfill({contentType:'text/event-stream',body:''});
  if(path==='/api/control/message'){followups.push(request.postDataJSON());return route.fulfill({json:{message_accepted:true,queued:true,mission_id:id}});}
  let json:unknown={};
  if(path==='/api/projects')json={projects:[{slug:'demo',title:'Demo'}]};
  else if(path==='/api/control/missions')json=[mission];
  else if(path===`/api/control/missions/${id}`)json=mission;
  else if(path.endsWith('/cloud'))json={mission_id:id,selection:{provider:'cursor_cloud',account:'cursor-default'},external_url:'https://cursor.com/agents/bc-test',turns:[{key:'first',prompt:'Prove one plus one',phase:++observations < 2 ? 'queued' : 'response_complete',external_id:'run-test',result:observations < 2 ? undefined : 'Two.',artifacts:[],branches:[]}]};
  else if(path==='/api/cloud/accounts')json=[{id:'cursor-default',provider:'cursor_cloud',label:'Cursor',available:true,capabilities:{follow_up:true,cancel:true}}];
  else if(path.endsWith('/files'))json={entries:[]};
  else if(path.endsWith('/crons'))json={jobs:[]};
  else if(path.includes('/controller'))json={job:null,runs:[]};
  else if(path==='/api/control/queue'||path==='/api/backends')json=[];
  else if(path==='/api/providers/backend-models')json={backends:{}};
  return route.fulfill({json});
 });
 await page.goto('/');
 await page.getByRole('button',{name:'Demo',exact:true}).click();
 await page.locator('button.row.agent').filter({hasText:'Cloud proof'}).click();
 await expect(page.getByText('Two.',{exact:true})).toBeVisible({timeout:10000});
 await expect(page.locator('.mission-lead .provider-logo > span')).toHaveCSS('width','15px');
 await expect(page.locator('.mission-lead .provider-logo > span')).toHaveCSS('mask-image', /cursor.svg/);
 await expect(page.getByRole('link',{name:'Open in Cursor Cloud'})).toHaveAttribute('href','https://cursor.com/agents/bc-test');
 await expect(page.getByRole('button',{name:'Change machine',exact:true})).toHaveCount(0);
 await page.reload();
 if (!(await page.locator('button.row.agent').filter({hasText:'Cloud proof'}).isVisible())) await page.getByRole('button',{name:'Demo',exact:true}).click();
 await page.locator('button.row.agent').filter({hasText:'Cloud proof'}).click();
 await expect(page.getByText('Two.',{exact:true})).toBeVisible({timeout:10000});
 await expect(page.locator('.mission-lead .provider-logo > span')).toHaveCSS('width','15px');
 await expect(page.locator('.mission-lead .provider-logo > span')).toHaveCSS('mask-image', /cursor.svg/);
 await page.getByPlaceholder('Continue this conversation…').fill('Explain the same result');
 await page.getByRole('button',{name:'Send',exact:true}).click();
 await expect.poll(()=>followups.length).toBe(1);
 expect(followups[0].mission_id).toBe(id);
 expect(followups[0].client_message_id).toMatch(/^[a-f0-9-]{36}$/);
});

test('section shortcuts and real model variants use the shared menus',async({page})=>{
 await page.addInitScript(()=>{localStorage.setItem('orb.apiUrl',location.origin);localStorage.setItem('orb.jwt','test');});
 const launches:any[]=[];
 await page.route('**/api/**',async route=>{
  const path=new URL(route.request().url()).pathname;
  if(path==='/api/control/stream')return route.fulfill({contentType:'text/event-stream',body:''});
  let json:unknown={};
  if(path==='/api/projects')json={projects:[{slug:'demo',title:'Demo'}]};
  else if(path==='/api/cloud/accounts')json=[{id:'chatgpt-profile',provider:'chatgpt',label:'ChatGPT · chatgpt-profile',available:true,experimental:true,capabilities:{models:true}},{id:'cursor-default',provider:'cursor_cloud',label:'Cursor Cloud',available:true,capabilities:{models:true}}];
  else if(path==='/api/cloud/chatgpt/options')json={models:{items:[{id:'gpt-6-pro',displayName:'GPT-6 Pro'},{id:'gpt-6-high',displayName:'GPT-6 High'}]}};
  else if(path==='/api/cloud/cursor/options')json={models:{items:[{id:'grok-4.6',displayName:'Grok 4.6',parameters:[{id:'effort',values:[{value:'high',displayName:'High'}]}],variants:[{isDefault:true,params:[{id:'effort',value:'high'}]}]}]},repositories:{items:[]}};
  else if(path==='/api/control/missions' && route.request().method()==='POST'){launches.push(route.request().postDataJSON());return route.fulfill({status:503,body:'Test submission ends here'});}
  else if(path==='/api/control/missions'||path==='/api/control/queue'||path==='/api/backends')json=[];
  else if(path.endsWith('/files'))json={entries:[]};
  else if(path.endsWith('/crons'))json={jobs:[]};
  else if(path.includes('/controller'))json={job:null,runs:[]};
  else if(path==='/api/providers/backend-models')json={backends:{}};
  return route.fulfill({json});
 });
 await page.goto('/');
 await page.getByRole('button',{name:'Cloud agent',exact:true}).waitFor();
 await page.keyboard.press('Meta+2');
 const form=page.getByRole('region',{name:'Cloud agent'});
 await expect(form.getByText('Profile 1',{exact:true})).toBeVisible();
 await expect(form.getByText('GPT-6 Pro',{exact:true})).toBeVisible();
 await expect(form.getByText('Experimental',{exact:true})).toHaveCount(0);
 await form.getByLabel('Model',{exact:true}).click();
 await form.getByRole('menuitemradio',{name:'GPT-6 High'}).click();
 await expect(form.getByText('GPT-6 High',{exact:true})).toBeVisible();
 await form.getByLabel('Service',{exact:true}).click();
 await form.getByRole('menuitemradio',{name:'Cursor Cloud'}).click();
 await expect(form.getByText('Grok 4.6 · High',{exact:true})).toBeVisible();
 await form.getByLabel('Prompt',{exact:true}).fill('Variant test');
 await form.getByRole('button',{name:'Create cloud agent'}).click();
 await expect.poll(()=>launches.length).toBe(1);
 expect(launches[0].cloud.model).toBe('grok-4.6');
 expect(launches[0].cloud.model_params).toEqual([{id:'effort',value:'high'}]);
 await page.keyboard.press('Meta+3');await expect(page.getByRole('button',{name:'Machines',exact:true})).toHaveClass(/active/);
 await page.keyboard.press('Meta+4');await expect(page.getByRole('button',{name:'Providers',exact:true})).toHaveClass(/active/);
 await page.keyboard.press('Meta+5');await expect(page.getByRole('button',{name:'Demo',exact:true})).toBeFocused();
});
