import { cleanup, fireEvent, render, screen, waitFor } from '@solidjs/testing-library';
import { afterEach, expect, it, vi } from 'vitest';
import { Composer } from '../src/App';
const handlers = new Map<string, (event: any) => void>();
afterEach(() => { cleanup(); handlers.clear(); delete (window as any).__TAURI__; vi.unstubAllGlobals(); vi.restoreAllMocks(); });
it('inserts all native local paths while the agent runs and deduplicates the relay', async () => {
  const invoke = vi.fn(), send = vi.fn();
  (window as any).__TAURI__ = { core: { invoke }, event: { listen: vi.fn(async (name, handler) => { handlers.set(name, handler); return () => handlers.delete(name); }) } };
  vi.stubGlobal('devicePixelRatio', 2);
  const view = render(() => <Composer placeholder="Drop here" uploadTarget="local" busy={true} onSend={send} onStop={() => {}} />);
  const composer = view.container.querySelector('.composer') as HTMLElement;
  vi.spyOn(composer, 'getClientRects').mockReturnValue([{}] as unknown as DOMRectList);
  vi.spyOn(composer, 'getBoundingClientRect').mockReturnValue({ left: 10, right: 310, top: 100, bottom: 200 } as DOMRect);
  const input = screen.getByPlaceholderText('Drop here') as HTMLTextAreaElement;
  fireEvent.input(input, { target: { value: 'Inspect: ' } });
  input.setSelectionRange(9, 9);
  const paths = ['/Users/test/Downloads/import.jsonl', '/Users/test/Downloads/import.json', '/Users/test/Downloads/import.txt'];
  await waitFor(() => expect(handlers.has('tauri://drag-drop')).toBe(true));
  expect((window as any).__TAURI__.event.listen).toHaveBeenCalledWith('tauri://drag-drop', expect.any(Function), { target: { kind: 'Webview', label: 'main' } });
  handlers.get('tauri://drag-drop')!({ payload: { paths, position: { x: 100, y: 300 } } });
  handlers.get('orb-upload-drop')!({ payload: { paths, x: 100, y: 300 } });
  await waitFor(() => expect(input.value).toBe('Inspect: ' + paths.map(path => '@' + path + ' ').join('')));
  expect(invoke.mock.calls.map(call => call[0])).not.toContain('read_upload_file');
  expect(invoke.mock.calls.map(call => call[0])).not.toContain('stage_upload_file');
  expect(send).not.toHaveBeenCalled();
  handlers.get('tauri://drag-drop')!({ payload: { paths: ['/outside.txt'], position: { x: 100, y: 50 } } });
  expect(input.value).not.toContain('outside');
  cleanup();
  await waitFor(() => expect(handlers.has('tauri://drag-drop')).toBe(false));
  expect(handlers.has('orb-upload-drop')).toBe(false);
});
